### ISSUE TITLE
serverless deploy did not fail even if the S3 bucket not exists

### ISSUE THREAD

**Issue by lardcas** [silvermine/silvermine-info#12]
Hi,

I noticed that the serverless deploy was completed even though S3 bucket name used in the Cloudfront Origin is not existing. Is there a way for us to handle those kind of scenario? Like if the S3 bucket used in the distribution origin is not exist, the deployment should not be proceed or completed.

Thanks,
Larry

**Comment by jthomerson** [comment]
Not related to this project.
