### ISSUE TITLE
Multiple Lambda@Edge Function Not Supported?

### ISSUE THREAD

**Issue by lardcas** [silvermine/silvermine-info#7]
Hi,

I was able to try using your plugin and it seems working fine, the code of Lambda@Edge has been updated and the updated Lambda@Edge function was attached to Cloudfront. Unfortunately, it seems the plugin does not support multiple Lambda@Edge functions? 

For instance, I want to have 3 Lambda@Edge Functions and each have their own folder which contains "index.js", see screenshot below for your reference.

![untitled](https://user-images.githubusercontent.com/41761993/52926574-501e6100-3371-11e9-885e-b078ae232b82.png)

When I run the serverless deploy command line, 3 Lambda@Edge Functions were created but the Cloudformation copied all 3 folders for each Lambda@Edge function. What I am expecting is that, the serverless will create 3 lambda@edge function and it will copy the correct folder.

Not sure though if this is just a config problem on my local instance or the problem relies on the serverless framework.

Any inputs from your end is highly appreciated. Thanks

Regards,
Larry DC

**Comment by lardcas** [comment]
This is what happened in my local AWS account for your reference.

![untitled2](https://user-images.githubusercontent.com/41761993/52927286-a8a32d80-3374-11e9-9f6c-44bbc825c492.png)

![untitled3](https://user-images.githubusercontent.com/41761993/52927288-a9d45a80-3374-11e9-893d-f709b31b1986.png)

**Comment by jthomerson** [comment]
@lardcas thanks for the report. Really, this issue should be opened up at https://github.com/silvermine/serverless-plugin-cloudfront-lambda-edge/, so if you have anything else to report, please open it there.

Your question really doesn't have anything to do with this plugin, though. The plugin doesn't do the packaging for you. Rather, that's done by the Serverless framework. You should be able to follow the examples here to package each function without the code from the others: https://serverless.com/framework/docs/providers/aws/guide/packaging#packaging-functions-separately

Hope that helps.
